<a href="https://colab.research.google.com/github/MonitSharma/Numerical-Linear-Algebra/blob/main/Multiplying_Matrices_and_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Author: [Monit Sharma](https://github.com/MonitSharma),
        LinkedIn: [Monit Sharma](https://www.linkedin.com/in/monitsharma/),
        Twitter: [@MonitSharma1729](https://twitter.com/MonitSharma1729)

In [1]:
# import numpy
import numpy as np

# avoid innacurate floating points 
np.set_printoptions(suppress=True)

# Introduction

We will see some very important concepts in this chapter. The dot product is used in every equation explaining data science algorithms so it's worth the effort to understand it. Then we will see some properties of this operation. Finally, we will to get some intuition on the link between matrices and systems of linear equations.

# Multiplying Matrices and Vectors

The standard way to multiply matrices is not to multiply each element of one with each elements of the other (this is the element-wise product) but to calculate the sum of the products between rows and columns. 

-----

The number of columns of the first matrix must be equal to the number of rows of the second matrix. Thus, if the dimensions, or the shape of the first matrix, is ($m\times n$) the second matrix need to be of shape ($n \times x$
). The resulting matrix will have the shape ($m \times x$
).




## Example 1

As a starter we will see the multiplication of a matrix and a vector

$$ {A} \times {b} = {C} $$

with ${A}=
\begin{bmatrix}
    1 & 2\\\\
    3 & 4\\\\
    5 & 6
\end{bmatrix}$ and $ {b}=\begin{bmatrix}
    2\\\\
    4
\end{bmatrix}$.

We saw that the formula is the following:

$$\begin{align*}
&\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}\times
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1}
\end{bmatrix}=\\\\
&\begin{bmatrix}
    A_{1,1}B_{1,1} + A_{1,2}B_{2,1} \\\\
    A_{2,1}B_{1,1} + A_{2,2}B_{2,1} \\\\
    A_{3,1}B_{1,1} + A_{3,2}B_{2,1}
\end{bmatrix}
\end{align*}$$

So we will have:

$$ \begin{align*}
&\begin{bmatrix}
    1 & 2 \\\\
    3 & 4 \\\\
    5 & 6
\end{bmatrix}\times
\begin{bmatrix}
    2 \\\\
    4
\end{bmatrix}=\\\\
&\begin{bmatrix}
    1 \times 2 + 2 \times 4 \\\\
    3 \times 2 + 4 \times 4 \\\\
    5 \times 2 + 6 \times 4
\end{bmatrix}=
\begin{bmatrix}
    10 \\\\
    22 \\\\
    34
\end{bmatrix}
\end{align*} $$

It is a good habit to check the dimensions of the matrix so see what is going on. We can see in this example that the shape of $A$
 is ($ 3 \times 2$
) and the shape of $b$
 is ($2 \times 1$
). So the dimensions of $C$
 are ($3 \times 1$
).


## With Numpy

The Numpy function `dot()` can be used to compute the matrix product (or dot product). Let's try to reproduce the last exemple:


In [2]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [4]:
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

It is equivalent to use the method `dot()` of Numpy arrays:

In [5]:
C = A.dot(B)
C

array([[10],
       [22],
       [34]])

## Example 2

Multiplication of two matrices

$$ {A} \times {B} = {C} $$

with 

$$ {A}=\begin{bmatrix}
    1 & 2 & 3 \\\\
    4 & 5 & 6 \\\\
    7 & 8 & 9 \\\\
    10 & 11 & 12
\end{bmatrix} $$

and 

$$ {B}=\begin{bmatrix}
    2 & 7 \\\\
    1 & 2 \\\\
    3 & 6
\end{bmatrix}$$

So we have:

$$ \begin{align*}
&\begin{bmatrix}
    1 & 2 & 3 \\\\
    4 & 5 & 6 \\\\
    7 & 8 & 9 \\\\
    10 & 11 & 12
\end{bmatrix}\times
\begin{bmatrix}
    2 & 7 \\\\
    1 & 2 \\\\
    3 & 6
\end{bmatrix}=\\\\
&\begin{bmatrix}
    2 \times 1 + 1 \times 2 + 3 \times 3 & 7 \times 1 + 2 \times 2 + 6 \times 3 \\\\
    2 \times 4 + 1 \times 5 + 3 \times 6 & 7 \times 4 + 2 \times 5 + 6 \times 6 \\\\
    2 \times 7 + 1 \times 8 + 3 \times 9 & 7 \times 7 + 2 \times 8 + 6 \times 9 \\\\
    2 \times 10 + 1 \times 11 + 3 \times 12 & 7 \times 10 + 2 \times 11 + 6 \times 12 \\\\
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    13 & 29 \\\\
    31 & 74 \\\\
    49 & 119 \\\\
    67 & 164
\end{bmatrix}
\end{align*} $$

Let's verify with `numpy`

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
B = np.array([[2, 7], [1, 2], [3, 6]])
B

array([[2, 7],
       [1, 2],
       [3, 6]])

In [8]:
C = A.dot(B)
C

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])

# Formalization of the dot product

$$ C_{i,j} = A_{i,k}B_{k,j} = \sum_{k}A_{i,k}B_{k,j} $$

## Properties of the dot product

We will now see some interesting properties of the matrix multiplication. It will become useful as we move forward in the chapters. Using simple examples for each property will provide a way to check them while we get used to the Numpy functions.


## Matrices multiplication is distributive

$$ {A}({B}+{C}) = {AB}+{AC} $$



## Example 3

$$ {A}=\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}, 
{B}=\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}, 
{C}=\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}$$


----

$$ \begin{align*}
{A}({B}+{C})&=\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\left(\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}+
\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}\right)=
\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    9 \\\\
    5
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    2 \times 9 + 3 \times 5 \\\\
    1 \times 9 + 4 \times 5 \\\\
    7 \times 9 + 6 \times 5
\end{bmatrix}=
\begin{bmatrix}
    33 \\\\
    29 \\\\
    93
\end{bmatrix}
\end{align*}$$


is equivalent to 

$$ \begin{align*}
{A}{B}+{A}{C} &= \begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}+
\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    2 \times 5 + 3 \times 2 \\\\
    1 \times 5 + 4 \times 2 \\\\
    7 \times 5 + 6 \times 2
\end{bmatrix}+
\begin{bmatrix}
    2 \times 4 + 3 \times 3 \\\\
    1 \times 4 + 4 \times 3 \\\\
    7 \times 4 + 6 \times 3
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    16 \\\\
    13 \\\\
    47
\end{bmatrix}+
\begin{bmatrix}
    17 \\\\
    16 \\\\
    46
\end{bmatrix}=
\begin{bmatrix}
    33 \\\\
    29 \\\\
    93
\end{bmatrix}
\end{align*}$$

In [9]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [10]:
B = np.array([[5], [2]])
B

array([[5],
       [2]])

In [11]:
C = np.array([[4], [3]])
C

array([[4],
       [3]])

$A(B+C)$

In [12]:
D = A.dot(B+C)
D

array([[33],
       [29],
       [93]])

is equivalent to $AB + AC$

In [13]:
D = A.dot(B) + A.dot(C)
D

array([[33],
       [29],
       [93]])

## Matrices mutliplication is associative

$$ {A}({BC}) = ({AB}){C} $$

In [14]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [15]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

$A(BC)$

In [16]:
D = A.dot(B.dot(C))
D

array([[100],
       [ 85],
       [287]])

is equivalent to $(AB)C$
:

In [17]:
D = (A.dot(B)).dot(C)
D

array([[100],
       [ 85],
       [287]])

## Matrix multiplication is not commutative

$$ {AB} \neq {BA} $$

In [18]:
A = np.array([[2, 3], [6, 5]])
A

array([[2, 3],
       [6, 5]])

In [19]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

$AB$ 

In [20]:
AB = np.dot(A, B)
AB

array([[16, 12],
       [40, 28]])

is different from $BA$

In [21]:
BA = np.dot(B, A)
BA

array([[28, 30],
       [16, 16]])

## However vector multiplication is commutative

$$ {x^{ \text{T}}y} = {y^{\text{T}}x}$$

In [22]:
x = np.array([[2], [6]])
x

array([[2],
       [6]])

In [23]:
y = np.array([[5], [2]])
y


array([[5],
       [2]])

${x^\text{T}y}$

In [24]:
x_ty = x.T.dot(y)
x_ty

array([[22]])

is equivalent to ${y^\text{T}x}$
: 

In [25]:
y_tx = y.T.dot(x)
y_tx

array([[22]])

## Simplification of the matrix product

$$ ({AB})^{\text{T}} = {B}^\text{T}
{A}^\text{T} $$

In [26]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [27]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

$({AB})^{\text{T}}$

In [28]:
AB_t = A.dot(B).T
AB_t

array([[16, 13, 47],
       [12, 11, 33]])

is equivalent to ${B}^\text{T}{A}^\text{T}$
: 

In [29]:
B_tA = B.T.dot(A.T)
B_tA

array([[16, 13, 47],
       [12, 11, 33]])